### ISSUE TITLE
Error in Big Sur Beta 10

### ISSUE THREAD

**Issue by number42bus** [chris1111/ASR-Clone-SSD-macOS-Catalina-Big-Sur#3]
After selecting  ✅  1 = ➖ ASR-Clone SSD - APFS

The below error is given

               =================================================== 
   
                         ASR-Clone SSD macOS Catalina Big Sur  
 
 
Clone SSD APFS
28:444: execution error: System Events got an error: Can’t make file "Macintosh SSD:System:Library:CoreServices:Expansion Slot Utility.app:Contents:Resources:AppIcon.icns" into type number or string. (-1700)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by chris1111** [comment]
thanks for the catch I will check but its look like a Beta bug  on AppleScript System Events

**Comment by chris1111** [comment]
Fix new release 
https://github.com/chris1111/ASR-Clone-SSD-macOS-Catalina-Big-Sur/releases/tag/V1
Now you have to select Catalina or Big Sur
![Capture d’écran, le 2020-10-17 à 00 29 51](https://user-images.githubusercontent.com/6248794/96328336-efe13600-100f-11eb-8ba2-92390e247152.png)
